### PR TITLE
Deriving Applicative for JobM.

### PR DESCRIPTION
**Pull request by cdepillabout**
In GHC 7.10, Applicative becomes a superclass of Monad.  Whenever an
instance of Monad is declared for a class, Applicative needs to be
declared as well.

https://wiki.haskell.org/Functor-Applicative-Monad_Proposal

### CODE REVIEW

**Comment by junjihashimoto** [comment]
Thanks!

Could you update .travis.yml for ghc7.10?

**Comment by cdepillabout** [comment]
I updated `.travis.yml` to test ghc 7.10.2 as well.  Let's see if it builds correctly.

**Comment by junjihashimoto** [comment]
Unfortunately, build fails.

**Comment by cdepillabout** [comment]
Yeah, I loosened up quickcheck's version bounds.  Lets see if this works.

**Comment by ikehara** [comment]
Oh, I can't recall the reason why I put this restriction to QuickCheck.
Sorry for the inconvenience and thank you for your contribution.

**Comment by cdepillabout** [comment]
It looks like `cabal build` is failing with the following error:

```
$ cabal build
Building jobqueue-0.1.5...
Preprocessing library jobqueue-0.1.5...
ghc: ghc no longer supports single-file style package databases (dist/package.conf.inplace) use 'ghc-pkg init' to create the database with the correct format.
```
https://travis-ci.org/gree/haskell-jobqueue/jobs/79418668#L862

I'm not sure how to solve this.

**Comment by junjihashimoto** [comment]
This is because cabal-install-1.18 is used.

**Comment by cdepillabout** [comment]
Okay, I changed the `.travis.yml` file to use cabal-1.22 when using ghc-7.10.2.  Let's see if it works this time.

**Comment by ikehara** [comment]
Awesome!

**Comment by cdepillabout** [comment]
Looks like it finally worked :+1:

**Comment by junjihashimoto** [comment]
great!

**Pull request merged**
