### PR TITLE
Add a stack.yaml for compiling with stack.

### PR DESCRIPTION
**Pull request by cdepillabout**
Adding a `stack.yaml` so that it is easier for people to contribute when
using `stack`.

### CODE REVIEW

**Comment by cdepillabout** [comment]
Maybe the resolver should be set to something like `lts-3.4` instead of a nightly release.

**Comment by junjihashimoto** [comment]
I think lts is better, too.

**Comment by cdepillabout** [comment]
I changed te resolver to lts-3.4.

**Comment by junjihashimoto** [comment]
LGTM!

**Comment by junjihashimoto** [comment]
I think jobqueue does not support monad-control > 1.*.

```stack build``` outputs following error.
```
$ stack build
jobqueue-0.1.4: configure
jobqueue-0.1.4: build
Progress: 1/2
--  While building package jobqueue-0.1.4 using:
      /home/junji-hashimoto/.stack/setup-exe-cache/setup-Simple-Cabal-1.22.4.0-x86_64-linux-ghc-7.10.2 --builddir=.stack-work/dist/x86_64-linux/Cabal-1.22.4.0/ build lib:jobqueue --ghc-options -hpcdir .stack-work/dist/x86_64-linux/Cabal-1.22.4.0/hpc/.hpc/ -ddump-hi -ddump-to-file
    Process exited with code: ExitFailure 1
    Logs have been written to: /home/junji-hashimoto/git/test7/haskell-jobqueue/.stack-work/logs/jobqueue-0.1.4.log

    Configuring jobqueue-0.1.4...
    Preprocessing library jobqueue-0.1.4...
    [ 8 of 18] Compiling Network.JobQueue.Types ( src/Network/JobQueue/Types.hs, .stack-work/dist/x86_64-linux/Cabal-1.22.4.0/build/Network/JobQueue/Types.o )
    
    src/Network/JobQueue/Types.hs:113:3:
        Wrong category of family instance; declaration was for a type family
        In the newtype instance declaration for ‘StT’
        In the instance declaration for ‘MonadTransControl (ActionT e a)’
    
    src/Network/JobQueue/Types.hs:121:3:
        Wrong category of family instance; declaration was for a type family
        In the newtype instance declaration for ‘StM’
        In the instance declaration for
          ‘MonadBaseControl base (ActionT e a m)’
```

**Comment by ikehara** [comment]
I could build this with support-ghc-7.10 branch on mac.
> git rebase support-ghc-7.10
> stack install --extra-include-dirs=/usr/local/include/zookeeper

**Comment by cdepillabout** [comment]
I'm able to install it as well on Linux.

```
$ stack build --test --extra-include-dirs ~/filesystem/zookeeper/include/zookeeper/ --extra-lib-dirs ~/filesystem/zookeeper/lib/
jobqueue-0.1.5: configure (test)
jobqueue-0.1.5: build (test)
jobqueue-0.1.5: test (suite: test)
```

**Comment by cdepillabout** [comment]
@junjihashimoto: Are you sure you're not compiling jobqueue-0.1.4?

**Comment by junjihashimoto** [comment]
Oh, I made a mistake.

**Comment by junjihashimoto** [comment]
I used master branch(jobqueue-0.1.4). So I made above mistake.

BTW, I guess  ```MONAD_CONTROL_VERSION="<= 0.3.3.0"``` of https://github.com/gree/haskell-jobqueue/blob/develop/.travis.yml#L2. is not needed.

**Comment by junjihashimoto** [comment]
No problem.
:bow:

**Pull request merged**
